services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    networks:
      - wpsite

  # WordPress
  wordpress:
    depends_on:
      - db
      - adminer
    image: wordpress:latest
    build:
      context: .
      dockerfile: Dockerfile.local  
      args:               
        LOCAL_UID: ${UID:-1000}
        LOCAL_GID: ${GID:-1000}
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_db
    networks:
      - wpsite

  # adminer (for database management)
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - '8081:8080'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_pass
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  wordpress:
  db:
